version: '2'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql2017
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: dockerSql2017
      TZ: Asia/Shanghai
    ports:
       - "1433:1433"
    # volumes:
    # - C:\sqlmnt:/var/opt/mssql
  redis:
    image: redis:6
    container_name: redis
    ports:
    - 6379:6379
  # plantuml:
  #   image: plantuml/plantuml-server:jetty
  #   container_name: plantuml-server
  #   ports:
  #   - 8080:8080
    
    #volumes:
    #- [your host path]:/data    
  # elasticsearch: 
  #   image: elasticsearch:6.6.1
  #   container_name: elasticsearch
  #   environment:
  #     discovery.type: single-node
  #   ports:
  #      - 9200:9200
  # kibana:
  #   image: kibana:6.6.1
  #   container_name: kibana
  #   ports:
  #   - 5601:5601
  #   links:
  #   - elasticsearch
  # sonarqube:
  #   image: sonarqube
  #   container_name: sonarqube
  #   restart: always
  #   ports: 
  #   - 9000:9000
  #   environment: 
  #     sonar.jdbc.url: jdbc:sqlserver://sqlserver;databaseName=sonar
  #     sonar.jdbc.username: sa
  #     sonar.jdbc.password: dockerSql2017
  #   links:
  #   - sqlserver