# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7.27
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci --lower_case_table_names=1 --sql_mode=allow_invalid_dates
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
  db_1:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
    ports:
      - 5432:5432
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080