# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080